### ISSUE TITLE
Sends alert for staff members when a player join (true/false) -- not working?

### ISSUE THREAD

**Issue by mrcoffee1026** [shadow5353/StaffNotes#1]
This option appears to be ignored?  Or there is an extra permission node to mark people as "staff" which you didn't list.  Also the Jenkins link everywhere is broken.

**Comment by shadow5353** [comment]
It have not yet been implemented, it will be added in the next update.
The Jenkins server have been shutdown, because I did not use it enough and I did not have the time to work on the plugin. I will soon begin on the plugin again.

**Comment by mrcoffee1026** [comment]
ok well if you update this or make a premium version i'll get it... i was otherwise just going to dump it when i update to 1.13 since without that feature it isn't of much use.  Only found like one other plugin similar to this and it sounded like it had a lot of issues, so hopefully you'll work on this one soon, thanks!
